#!/usr/bin/env node
// Vendor the design system's icons into crates/ui_kit/icons and regenerate
// the compile-time table crates/ui_kit/src/icon_table.rs.
//
// Each source SVG is 24×24, 1.5px stroke, `currentColor`. The copy drops
// the embedded provenance metadata, paints the strokes white so a texture
// tints at draw time, and renames or skips a few files: the app's document
// icon carries a neutral name, and icons for features outside the Part
// Design and Sketcher scope are not vendored.
//
// Run: node scripts/vendor-icons.mjs [<source icon dir>]  (default ui-mockup/icons)

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const src = process.argv[2] ?? join(root, "ui-mockup", "icons");
const dest = join(root, "crates", "ui_kit", "icons");
const table = join(root, "crates", "ui_kit", "src", "icon_table.rs");

// The source names its document icon after its own file format; the copy
// carries a neutral name. Exactly one `file-*` icon is expected.
const DOCUMENT_ICON = "file-document";
const SKIP = new Set([
  "migrate", "sprocket", "involute-gear", "shape-binder", "sub-shape-binder",
  "constraint-refraction", "switch-virtual-space", "tree-spreadsheet",
  "workbench-spreadsheet",
  // The source draws this one with a text glyph, which needs a font the
  // rasterizer does not carry; the local copy is pure geometry.
  "expression",
]);
// Icons authored in this repo (not part of the source set) that the table
// must keep.
const LOCAL = new Set([
  "select", "expression",
  // The 6-DoF mouse gestures, drawn here because no icon set has them.
  "gesture-slide-x", "gesture-slide-y", "gesture-slide-z",
  "gesture-tilt", "gesture-twist", "gesture-rock",
]);

mkdirSync(dest, { recursive: true });
for (const f of readdirSync(dest)) {
  if (f.endsWith(".svg") && !LOCAL.has(f.slice(0, -4))) unlinkSync(join(dest, f));
}

const names = [];
for (const file of readdirSync(src).sort()) {
  if (!file.endsWith(".svg")) continue;
  const base = file.slice(0, -4);
  if (SKIP.has(base)) continue;
  const name = base.startsWith("file-") ? DOCUMENT_ICON : base;
  if (name === DOCUMENT_ICON && names.includes(DOCUMENT_ICON)) {
    console.error(`vendor-icons: more than one file-* icon in the source set`);
    process.exit(1);
  }
  let svg = readFileSync(join(src, file), "utf8");
  svg = svg.replace(/<metadata>.*?<\/metadata>/s, "");
  svg = svg.replace(/\s+xmlns:c2pa="[^"]*"/, "");
  svg = svg.replace(/currentColor/g, "#FFFFFF");
  svg = svg.replace(/>\s+</g, "><").trim() + "\n";
  writeFileSync(join(dest, `${name}.svg`), svg);
  names.push(name);
}
for (const local of LOCAL) {
  if (!existsSync(join(dest, `${local}.svg`))) {
    console.error(`vendor-icons: missing local icon ${local}.svg`);
    process.exit(1);
  }
  names.push(local);
}
names.sort();

const rows = names.map((n) => `    ("${n}", include_str!("../icons/${n}.svg")),`).join("\n");
writeFileSync(
  table,
  `// Generated by scripts/vendor-icons.mjs — do not edit by hand.\n` +
    `// One entry per file in crates/ui_kit/icons, sorted by name.\n\n` +
    `pub const ICONS: &[(&str, &str)] = &[\n${rows}\n];\n`,
);
console.log(`vendored ${names.length} icons`);
